services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.13.0
    ports:
      - "5500:5000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow.db
    volumes:
      - ./mlruns:/mlflow-artifacts
      - ./mlflow.db:/mlflow/mlflow.db
    command: >
      mlflow server
        --backend-store-uri sqlite:///mlflow.db
        --artifacts-destination /mlflow-artifacts
        --serve-artifacts
        --host 0.0.0.0
        --port 5000
